language: rust

env:
  CODECOV_TOKEN=26857aee-2ccc-448c-bf70-fcb35af6b3b5

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

script:
  - rustc --version
  - cargo --version
  - cargo test --all --verbose
  - cargo build

notifications:
  email:
    - on_success: change
    - on_failure: always
