[package]
name = "ratel"
version = "0.1.0"
authors = ["DanielMorton <dacmorton@gmail.com>"]
description = "Rust Implementation of a Muti-armed Bandit Simulator."
edition = "2018"
repository = "https://github.com/DanielMorton/ratel"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "*"
clap = "*"
itertools = "*"
lazy_static = "*"
num-traits = "*"
rand = "*"
rand_distr = "*"
scoped_threadpool="*"