[package]
name = "ratel"
version = "0.1.0"
authors = ["DanielMorton <dacmorton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_approx_eq = "*"
clap = "*"
itertools = "*"
lazy_static = "*"
num-traits = "*"
rand = "*"
rand_distr = "*"
scoped_threadpool="*"