version: 2.1
jobs:
  build54:
    docker:
      - image: circleci/rust:1.54
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build53:
    docker:
      - image: circleci/rust:1.53
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build52:
    docker:
      - image: circleci/rust:1.52
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build51:
    docker:
      - image: circleci/rust:1.51
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build50:
    docker:
      - image: circleci/rust:1.50
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build49:
    docker:
      - image: circleci/rust:1.49
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build48:
    docker:
      - image: circleci/rust:1.48
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build47:
    docker:
      - image: circleci/rust:1.47
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build46:
    docker:
      - image: circleci/rust:1.46
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build45:
    docker:
      - image: circleci/rust:1.45
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build44:
    docker:
      - image: circleci/rust:1.44
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build43:
    docker:
      - image: circleci/rust:1.43
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build42:
    docker:
      - image: circleci/rust:1.42
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build41:
    docker:
      - image: circleci/rust:1.41
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build40:
    docker:
      - image: circleci/rust:1.40
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
workflows:
  version: 2
  rust:
    jobs:
      - build54
      - build53
      - build52
      - build51
      - build50
      - build49
      - build48
      - build47
      - build46
      - build45
      - build44
      - build43
      - build42
      - build41
      - build40