version: 2
jobs:
  build44:
    docker:
      - image: circleci/rust:1.44
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build43:
    docker:
      - image: circleci/rust:1.43
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build42:
    docker:
      - image: circleci/rust:1.42
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build41:
    docker:
      - image: circleci/rust:1.41
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build40:
    docker:
      - image: circleci/rust:1.40
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build39:
    docker:
      - image: circleci/rust:1.39
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build38:
    docker:
      - image: circleci/rust:1.38
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build37:
    docker:
      - image: circleci/rust:1.37
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build36:
    docker:
      - image: circleci/rust:1.36
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build35:
    docker:
      - image: circleci/rust:1.35
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build34:
    docker:
      - image: circleci/rust:1.34.2
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build33:
    docker:
      - image: circleci/rust:1.33
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build32:
    docker:
      - image: circleci/rust:1.32
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
workflows:
  version: 2
  rust:
    jobs:
      - build39
      - build38
      - build37
      - build36
      - build35
      - build34
      - build33
      - build32