version: 2
jobs:
  build38:
    docker:
      - image: circleci/rust:1.38-buster
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build37:
    docker:
      - image: circleci/rust:1.37-buster
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build36:
    docker:
      - image: circleci/rust:1.36-buster
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
  build35:
    docker:
      - image: circleci/rust:1.35
    steps:
      - checkout
      - run: cargo test --all --verbose
      - run: cargo build
workflows:
  version: 2
  rust:
    jobs:
      - build38
      - build37
      - build36
      - build35